{% set name = "sf-hamilton" %}
{% set version = "1.50.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sf-hamilton-{{ version }}.tar.gz
  sha256: 84730e28c321a3bc31aa908222daf8a53a619c45f45f7a425786818c138b2c2f


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4
  run:
    - numpy
    - pandas
    - python >=3.7,<4
    - typing_extensions >4.0.0
    - typing_inspect

test:
  imports:
    - hamilton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DAGWorks-Inc/hamilton
  summary: Hamilton, the micro-framework for creating dataframes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
