{% set name = "sf-hamilton" %}
{% set version = "1.67.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4b995d28df9aff29d30624e9ce483bb4b876a82a812809ba079b3f042a22b4a2


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4
  run:
    - numpy
    - pandas
    - python >=3.7,<4
    - typing_extensions >4.0.0
    - typing_inspect

test:
  imports:
    - hamilton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DAGWorks-Inc/hamilton
  summary: Hamilton, the micro-framework for creating dataframes.
  doc_url: https://hamilton.dagworks.io/en/latest/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
